# Generated by Django 3.1 on 2023-08-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color selector'), ('size', 'size selector')], max_length=100),
        ),
    ]
